var data = [
["Slecht", "Goed"],
["Licht verslavend", "Zeer verslavend"],
["Heet", "Verkoudheid"],
["Normaal", "Raar"],
["Kleurloos", "Kleurrijk"],
["Laag in calorieën", "Hoog in calorieën"],
["Het voelt slecht", "Voelt goed"],
["Onbelangrijk", "Essentieel"],
["Goedkoop", "Duur"],
["Onderschat wapen", "Overschat wapen"],
["Bijzonder", "Gemeenschappelijk"],
["Unsexy emoji", "Sexy emoji"],
["Makkelijk onderwerp", "Moeilijk onderwerp"],
["Onbekend", "Beroemd"],
["Moeilijk te gebruiken", "Makkelijk te gebruiken"],
["Vies", "Schoon"],
["Vereist geluk", "Vereist vaardigheid"],
["Smakeloos", "Smaakvol"],
["Saai onderwerp", "Fascinerend onderwerp"],
["Slechte acteur", "Goede acteur"],
["Gevaarlijke baan", "Veilige baan"],
["Fantasy", "Sci-Fi"],
["Gewoontjes", "Formeel"],
["Onderbetaald", "Overbetaald"],
["Droog", "Nat"],
["Onderschatte vaardigheid", "Overschatte vaardigheid"],
["Verboden", "Aangemoedigd"],
["Verdrietig lied", "Vrolijk lied"],
["Breekbaar", "Duurzaam"],
["Goed", "Slecht"],
["Slechtste dag van het jaar", "Beste dag van het jaar"],
["Slechte gewoonte", "Goede gewoonte"],
["Kattenpersoon", "Hondpersoon"],
["Guilty pleasure", "Eigenlijk gewoon goed"],
["Ongetalenteerd", "Getalenteerd"],
["Donker", "Licht"],
["Onderschatte acteur", "Overschatte acteur"],
["Moeilijk te vinden", "Makkelijk te vinden"],
["Lelijke man", "Mooie man"],
["Moeilijk te onthouden", "Makkelijk te onthouden"],
["Trashy", "Elitair"],
["Ongezond", "Gezond"],
["Slechte man", "Goede man"],
["Historisch belangrijk", "Historisch niet relevant"],
["Haarloos", "Harig"],
["Onflexibel", "Flexibel"],
["Normaal huisdier", "Exotisch huisdier"],
["Introvert", "Extravert"],
["Boek was beter", "Film was beter"],
["Slechte film", "Goede film"],
["Lelijk", "Mooi"],
["Gebeurt langzaam", "Gebeurt plotseling"],
["Geliefd", "Gehaat"],
["Slechte pizza-topping", "Goede pizza-topping"],
["Dystopie", "Utopie"],
["Onderschat ding om te bezitten", "Overschat ding om te bezitten"],
["Gemeen persoon", "Aardig persoon"],
["Actiefilm", "Avonturenfilm"],
["Mentale activiteit", "Fysieke activiteit"],
["Onomstreden onderwerp", "Controversieel onderwerp"],
["Nodig hebben", "Willen"],
["Normaal om te bezitten", "Raar ding om te bezitten"],
["Slecht persoon", "Goed persoon"],
["Jaren 80", "Jaren 90"],
["Ethisch om te eten", "Onethisch om te eten"],
["Optioneel", "Verplicht"],
["Ondergewaardeerde letter van het alfabet", "Overschatte letter van het alfabet"],
["Gewoon", "Raar"],
["Moeilijk uit te spreken", "Makkelijk uit te spreken"],
["Lage kwaliteit", "Hoge kwaliteit"],
["Unsexy dier", "Sexy dier"],
["Gewoon", "Luxe"],
["Heeft een slechte reputatie", "Heeft een goede reputatie"],
["Slecht gemaakt", "Goed gemaakt"],
["Geen sandwich", "Een sandwich"],
["Stille plek", "Luide plek"],
["Komedie", "Drama"],
["Gevaarlijk", "Veilig"],
["Cultureel significant", "Cultureel onbeduidend"],
["Vervangbaar", "Onvervangbaar"],
["Slechtste atleet aller tijden", "Beste atleet aller tijden"],
["Rolmodel", "Slechte invloed"],
["Nutteloze opleiding", "Nuttige opleiding"],
["Vredig", "Oorlogszuchtig"],
["Onderschatte film", "Overschatte film"],
["Ruw", "Glad"],
["Slecht voor je", "Goed voor je"],
["Afgerond", "Puntig"],
["Treurige film", "Feel-good film"],
["Tijdsverspilling", "Goed gebruik van tijd"],
["Eng dier", "Leuk dier"],
["Mainstream", "Niche"],
["Duurt kort", "Duurt lang"],
["Niemand doet het", "Iedereen doet het"],
["Stinkt", "Ruikt lekker"],
["Star Wars", "Star Trek"],
["Snack", "Maaltijd"],
["Minst slecht bedrijf", "Slechtste bedrijf"],
["Zacht", "Moeilijk"],
["Levensonderhoud", "Haute cuisine"],
["Vierkant", "Rond"],
["Beter heet", "Beter koud"],
["Dom", "Briljant"],
["Ambachtelijk", "Massa-geproduceerd"],
["Slechte superkracht", "Goede superkracht"],
["Niet effectief", "Effectief"],
["Ongelofelijk", "Ongelooflijk"],
["Trashy", "Stijlvol"],
["Tijdelijk", "Permanent"],
["Lijkt op een persoon", "Lijkt niet op een persoon"],
["Smaakt slecht", "Smaakt goed"],
["Sport", "Spel"],
["Niet cool", "Cool"],
["Slechtste levende persoon", "Grootste levende persoon"],
["Onderschat", "Overschat"],
["Rommelig eten", "Schoon eten"],
["Onethisch", "Ethisch"],
["Slecht cadeau", "Goed cadeau"],
["Modieus", "Modieus"],
["Vrijheidsvechter", "Terrorist"],
["Mislukking", "Meesterwerk"],
["Onschadelijk", "Schadelijk"],
["Griffoendor", "Zwadderich"],
["Onhygiënisch", "Hygiënisch"],
["Slechte muziek", "Goede muziek"],
["Nutteloos", "Nuttig"],
["Film die Godzilla zou verpesten", "Film die Godzilla zou verbeteren"],
["Onbelangrijk", "Belangrijk"],
["Makkelijk te spellen", "Moeilijk te spellen"],
["Ondeugd", "Deugd"],
["Onderschatte muzikant", "Overschatte muzikant"],
["Impopulaire activiteit", "Populaire activiteit"],
["Onbetrouwbaar", "Betrouwbaar"],
["Makkelijk te doden", "Moeilijk te doden"],
["Onstabiel", "Stabiel"],
["Rond dier", "Puntig dier"],
["Slechte tv-show", "Goede tv-show"],
["Traditioneel mannelijk", "Traditioneel vrouwelijk"],
["Nutteloos lichaamsdeel", "Handig lichaamsdeel"],
["Hype", "Classic"],
["Zwak", "Sterk"],
["Walgelijk ontbijt", "Heerlijk ontbijt"],
["Nutteloze uitvinding", "Nuttige uitvinding"],
["Liberaal", "Conservatief"],
["Impopulair", "Populair"],
["Vriend", "Vijand"],
["Saai", "Spannend"],
["Stinkt op een slechte manier", "Stinkt op een goede manier"],
["Schurk", "Held"],
["Onderschat ding om te doen", "Overschat ding om te doen"],
["Nutteloos in noodgevallen", "Handig in noodgevallen"],
["Voor kinderen", "Voor volwassenen"],
["Wijs", "Intelligent"],
["Makkelijk te doen", "Moeilijk om te doen"],
["Waardeloos", "Onbetaalbaar"],
["Aangeboren", "Aangeleerd"],
["Dictatuur", "Democratie"],
["Normale begroeting", "Rare begroeting"],
["Naam voor een hond", "Naam voor een kat"],
["Onafhankelijk", "Partijdig"],
["Beperkt", "Eindeloos"],
["Casual evenement", "Formeel evenement"],
["Slechte investering", "Goede investering"],
["Koetjes en kalfjes", "Zwaar onderwerp"],
["Mild", "Pittig"],
["Religieus", "Heiligschennend"],
["Geen kunst", "Kunst"],
["Populair", "Elitair"],
["Uit de hand", "Onder controle"],
["Rustig", "Luid"],
["Geheim", "Algemeen bekend"],
["Te klein", "Te groot"],
["Kort", "Lang"],
["Slechtste jaar ooit", "Beste jaar uit de geschiedenis"],
["Socialistisch", "Kapitalistisch"],
["Weinig bekend feit", "Bekend feit"],
["Lokaal probleem", "Wereldwijd probleem"],
["Talent", "Vaardigheid"],
["Slechtste tijd om naar te tijdreizen", "Beste tijd om naar te tijdreizen"],
["Het ergste", "Het beste"],
["Klein getal", "Groot getal"],
["1", "0"],
["Oubollig", "Avant-garde"],
["Lelijk woord", "Prachtig woord"],
["Onnatuurlijk", "Natuurlijk"],
["Namaak", "Origineel"],
["Unsexy kleur", "Sexy kleur"],
["Goed vour jou", "Goed voor iedereen"],
["Machteloos", "Krachtig"],
["Verdampt niet", "Verdampt"],
["Fruit", "Groente"],
["Wetenschap", "Pseudowetenschap"],
["Grappig onderwerp", "Serieus onderwerp"],
["Slap", "Stevig"],
["Guilty pleasure", "Eigenlijk gewoon slecht"],
["Roddel", "Nieuws"],
["Moeilijk om op te zitten", "Makkelijk om op te zitten"],
["Niet genoeg", "Te veel"],
["Horizontaal", "Verticaal"],
["Geen geur", "Sterke geur"],
["Knuffelbaar", "Niet knuffelbaar"],
["Inclusief", "Exclusief"],
["Slecht hondenras", "Goed hondenras"],
["Kunst", "Commercie"],
["Eendagsvlieg", "Pop icoon"],
["Slecht advies", "Goede raad"],
["Slecht snoep", "Goed snoep"],
["Traditioneel", "Radicaal"],
["Kraakt", "Sappig"],
["Onwettig", "Juridisch"],
["Diepe gedachte", "Ondiepe gedachte"],
["Nooit op tijd", "Altijd op tijd"],
["Zal niet 100 worden", "Zal leven tot 100"],
["Slecht Disney-personage", "Goed Disney-personage"],
["Vergelijkbaar", "Identiek"],
["Raar", "Vreemd"],
["Beroemd", "Berucht"],
["Minst krachtige god", "Krachtigste god"],
["Saai persoon", "Leuk persoon"],
["Onderschat boek", "Overschat boek"],
["Ergste klus", "Leukste klus"],
["Bedreigde soort", "Overbevolkte soort"],
["Blauw", "Groen"],
["Spannend", "Angstaanjagend"],
["Verwacht", "Onverwacht"],
["Persoon die je in elkaar zou kunnen slaan", "Persoon die jou in elkaar zou slaan"],
["Onredelijke fobie", "Redelijke fobie"],
["Ondergewaardeerd spel", "Overschat spel"]
];
